version: "3.8"

volumes:
  app_data:
    name: app_data
  app_broker:
    name: app_broker

services:
  django: &django
    image: cognito:development
    command: /app/config/start.sh server
    depends_on:
      - postgres
    env_file:
      - config/.env
    ports:
      - "8001:8000"
  
  postgres:
    image: postgres:13.3-alpine
    volumes:
      - app_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  
  # redis:
  #   image: redis:alpine
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - app_broker:/var/lib/redis/data
  
  # celery:
  #   <<: *django
  #   depends_on:
  #     - django
  #     - postgres
  #     - redis
  #   ports:
  #     - "8002:8000"
  #   command: /app/config/start.sh worker
  
  # beat:
  #   <<: *django
  #   depends_on:
  #     - django
  #     - postgres
  #     - redis
  #   ports:
  #     - "8003:8000"
  #   command: /app/config/start.sh beat